using QuoteApi.Models;
using QuoteApi.Repositories;
using QuoteApi.Services;
using QuoteApi.Middlewares;
using QuoteApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddScoped<IQuoteService,QuoteService>();
builder.Services.AddScoped<IRepository<Quote,QuoteApiDbContext>,Repository<Quote,QuoteApiDbContext>>();
builder.Services.AddScoped<IRepository<Author,QuoteApiDbContext>,Repository<Author,QuoteApiDbContext>>();
builder.Services.AddScoped<IRepository<AuthorAudit,QuoteApiDbContext>,Repository<AuthorAudit,QuoteApiDbContext>>();
builder.Services.AddSingleton<NewQuoteNotifier>();
builder.Services.AddOpenApi();
string connectionString = builder.Configuration.GetConnectionString("QuoteApi") ?? throw new InvalidOperationException("Connection string to QuoteApi database not found");
builder.Services.AddDbContext<QuoteApiDbContext>((options)=>options.UseNpgsql(connectionString));
WebApplication app = builder.Build();
app.UseMiddleware<ExceptionHandlingMiddleware>();
app.MapControllers();
app.MapOpenApi();
app.Run();