using QuoteApi.Models;
using QuoteApi.Repositories;
using QuoteApi.Services;
using QuoteApi.Middlewares;
using QuoteApi.Data;
using Microsoft.EntityFrameworkCore;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddSingleton<IQuoteService,QuoteService>();
builder.Services.AddSingleton<IRepository<Quote>,Repository<Quote>>();
builder.Services.AddSingleton<NewQuoteNotifier>();
builder.Services.AddOpenApi();
builder.Services.AddDbContext<QuoteApiDbContext>((options)=>options.UseNpgsql("Host=localhost;Port=5432;Database=quoteapi;Username=yanishgooradoo"));
WebApplication app = builder.Build();
IRepository<Quote> repository = app.Services.GetRequiredService<IRepository<Quote>>();
app.Services.GetRequiredService<NewQuoteNotifier>();
await repository.AddAsync(new(1,"testing"));
app.UseMiddleware<ExceptionHandlingMiddleware>();
app.MapControllers();
app.MapOpenApi();
app.Run();
